### ISSUE TITLE
I need permission access to push my branch `feature/header` to wcn-website repo

### ISSUE THREAD

**Issue by sunsplat** [womencodersnetwork/wcn-website#30]
## Expected Behavior
I can make changes locally on my computer and push those changes up to git@github.com:womencodersnetwork/wcn-website.git using either http or ssh

## Current Behavior
I am seeing the following error when trying to push:
```
ERROR: Permission to womencodersnetwork/wcn-website.git denied to sunsplat.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Possible Solution
Add permissions to push to repo for users participating in the website contribution

## Context
I can't create a pull request to merge my updates for website without this permission, for update related to TODO item: https://github.com/orgs/WomenCodersNetwork/projects/1/views/1?pane=issue&itemId=64016013

## Your Environment
Using VS Code on a MacOS

github username: sunsplat

**Comment by createHernandez** [comment]
This action has been documented in https://github.com/womencodersnetwork/wcn-website/issues/3 as a comment instead. Therefore this issue will be closed as a duplicate.
